language: java
jdk:
- oraclejdk8
branches:
  except:
  - travis
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
env:
  global:
    secure: "i0mYZY6Pmg4J7kwcx3fkNpMATMH505asK4lGzv0HzpaVnwRbJ7lby6apHIVyuG9jcai+Dt3WDKTbY+ChvixoKQET45TcszpHbpaEph/o2OhdOhJq4JLk7y6+62YU/fuynvgvxQ7mhrLJLok3IpNZ/qz0EZ/YdjpXRcg5EPqRejBk4O1R4J0OhS3zV+C6eODPjiMTkaOzGp+ndd/2+8QqtI/PZTsNMcFxsBBtyrdBd6OClFUdEMrL3cO2J1T3YKxCCJGhkvAm0BvaEjBUC607jO5XqBu71PsDRa3W8J9XAfuGvHwSyXL6N/YEZjlEB1uxW8FGQsNJnpl6KSMYhpjQYwjpUyAQLqO/4RmrZNLHd93j3U8nQOUUETJnYv2jQus/61/6M203UIkvnblNV5/75m432Pyav7eYwG5UcjhTgx7swVo0pfkHfka2jrFHQYZYV87F28h9hSyM8iy3d8RxUmGEIOO6COk0zPTa6AZYgYEXh1aPdbTHAEpBYwLjM2pY01i6/ydmT6YxDhS5UmuRtIKkTbXfQ6nPblEnaE0yZWWETiGqsepk0Mle3clKO3VjkpKJB89W0IZT7Bm+g3kk/Qq2SDxf7Hfp+fAeuOYyCFk4lumpgMnBouhseHuY2R6s86WI3ES+I6/gQAJvPj4aqcV0PdIHWbJjHu5q71jmHWQ="
    secure: "ti6do5KTCo276vMSWv6hHZAopF/rDICC5PiEkwLkv8TCJAAwYSqK0qeg2Wm8UlMFz/4lOrWW/jK2XEsIXROo0/7zNoYZ5v4yY4fUTCTVevB0BvKsN7In/ZaNpD0n4mJcRxi/4RHZ0nfmSq+9Y8+ZtcouKv0qH9YNDOS7YfhaF4n219GTrNBPDH5XWNTC1jbL32EXw3atR9lhMhG5C6YPP+XL8n5Hdh47Yj2mgUe17zVUV86Nd5Lca7dPE7keX3C0CVYQaxfzQYm71JvfQsxs2RbN+bK+VfPB84I10t1nq9/8tuA/4chXHyrELk1ZFu01RIxV4SMp+Bp34CLrY2/uj/o5TLH7KeuCXhiLQ9f7C9gLex+nT+J0lE86eWndeWMYCltTcbDj2pURwtVxTkuLZAsGqixthihDFrgAJowZvt1ypuW33dm6e4PVF5SQfQpGStSmIh1JPaGqhOTMEbd4SbhPCSKBiVLsiN07WhHucS8dO4FQJOm/VLQvgJWOkruKI9cC/lH9rJ2a8cHEQYh3vAwdIthwAyz64uPoFyCWTnc42gFhqi77ysiFLmYRdW+y51HW2v0iw9GygbLQ2m4GEWhtiFPoZrnQwjCanxAq/Dv1xHoVw/MfkOd4YGtV0jSTSX/0sTnf4zQiTmbeiqB/aYO+GuUKPi+r6MGK956Eibs="
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script:
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c  "mvn deploy --settings
  target/travis/settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c "mvn clean install" ;fi
