language: java
jdk:
- oraclejdk8
branches:
  except:
  - travis
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
env:
  global:
    secure: "aOLr3Ob8rcRlaRhFJlBAD7ROF4qx3lL8MlAAfg782hIdaNTmZoXXT3X9EnH69ELDH9zzZEtYXaFIM24/ZTj6kdTfa+b/qBh7cC+h1/sMv7+scRtfeCFcBCS7t29Nq6rNTms19/Ccn+yZRR9lvhmkdxw6kdyY0OIrD9LEg4y+8VSbELgAM3+8a5LPFsFXkrRNzCnff5pLEC6aPkWXIEdN7xBoDzqlmwNZplCZTVRIw5j011Impeuw39mmax71r7EXiQuunv+VmQ+rNmT6yozAwDtJb37AzjDHW9cFwSB4GV+87F9BnvkM3QRcnk4AFkF1z7ByQNPymnt0Mr236e5skTR2zWDqv0sNK8jDGIVItBHxQHHYCGdTDjOH0FDp77FJqcxZMG9/1DhInTpjnjUXJCe2Gl2++Fyo1x2plA+wRk/qBPZ3WUhuQ+oJvyajep5hIfM4I5puWs80CC8TTWDqS7PAdIzK2qSk79Ijf6to1uPaBStDFR0eRhzwpsfXbSJedh+v18Rm0mdBAdhy5n13ZuNpCTFgGnkEZqpjqV43/zCDsb+W8rA2d0ZFQpqyRYYVKvnAinde8wechx/Dl1w+EjlKimYhKL6wA+w9PllTFUr4bJNHkbNIfQYGSWKdyeX7BPUBAL1nzWi5XGoGdqvMjlx+1FGR+JxVr4jMZY+U4rM="
    secure: "2lwwtMNNJUqathW6T3aBshubEctXfF75yszbBcomfDYSjFsYMjZKR69V9D9q0OEGGxitvEEHhj3FErKquOOVI54dU6aAukM+Yh+RvoRp0R7zxOUo1xlTFR6Fs/RGGDnSb0w2T0iRCY5fnw8cIJxXTp82P772u9jE6HEWV2fxN1eJKv1CRfPlAF4FfiMYTiH519kwKKAseblxM9FBSYVGyPVDwqW+CHDblU8vSfDlD+YUjfMhOgmO/CBAw4pW8iLa6bGJPT0fYwxXFrIc5uOMPjtUPvpaWbyBVBtOfvt4MqeraMyk2eKKKcqpif6gIJmWIEeNC4WJ9ZPBvCH9otDB4L6nvVj7wTt0caiE1KjSJXDPEzIj5DrzK/s+cxPD3YMosYbJMqnwveuOTporYtYIzZeWzH9IIy9vpzkIO6iVvO8Xvx1Xezkcmyhf/bi786GG7McnqPGJp6Ykkp7IIR/LKMwZiBEUvxWyl8fsTwYMtj6Rw0VHR733aGT98/Pn9CJc02f1vSkj5vcb9pVLMoyqSHqGa4FcBWdzmUkp1O2fuqSXaBaCiTxsYnS9W5j4jJuxKVc1GJOqCinA4l50UzGTx5hynZvhHpfaA4Ma87jtgrcgkTXB6YlaZtHy6dQ20cvg2DxSeQlIoywrz46uXDFnciBXDgVDzU+pzwokQ8Wma4o="
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script:
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c  "mvn deploy --settings
  target/travis/settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c "mvn clean install" ;fi
