language: java
jdk:
- oraclejdk8
branches:
  except:
  - travis
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
env:
  global:
    secure: nNcO1FT071EJMMAlmJEOZm2HXn+GhleAJO8pLv0ReOk4RC3uYE2t7igsoPrIlkTXOK6c//EpIPXUgcjkHSTi55FY9DdPVT3trnMdOv693uXsLuiX3ck3ugaAkIuOyyLNn+SP7fYrpabuMwwRLkJJIKeTA+2CdLgbQuX2iQwgBfjbSIRMxNGv6yfW5OZLrcmR4uFUoAttPmGdrmHut2z7nm3n+5Ebj9p2CAUcGoI8FZROw4fnLb9uctsRRgASkcQd9Y1OKyzfAaBhWmVQnMmfMJ+1OUoMs2y+1niXp3qWzRL9B4pTdp6hch9f2BSux71nwm39U/sN13bZmSYfND+VF0+RaR98Eu4TBduzUdweShn2DeBKJK8u1WVYQ46qoI7X2sGv+pHn6nY5EpesEBmXB/xp6i7X1DNlNzClwci+DH9IHOPcKqE4i1z6N6TzaW4rEkFrlfH9xO/eMe3iX3QyK+Fq5D7gImUhRLWC2lAoNQCaCzsvmbptUuPioDh3XFLqM0/z08BgxfmvdLnni6c99VmFPJOL8ojcpeM6xjOONmQFO1kttRLkmRRTEowrWVFsINisjmg9GNDCJR3Q1A5wTJOgNsHfcC/oTw0BeBAy5t4xsJr0rI1oS5k6T50oQiVy7FggPer+Y1fjRQJ0DzwdnahCpMxyXyxUMDVXEYRe+ak=
    secure: oVOnp9eogj+mKLUV1bNSpqreZ0y4NscodA+L8mpnvY8vY057xxSw+k9TND4z7DIHRUAwoec5fhAiRxTvwfPnDK73KYd26smJjAyDqKfrnVArEdWR3eg5tNcZnnUXZBXkvWgeNnJSKUTaGlmF8r3yruNS5vYuuNLzH7NCC5mRH0NYdCfLnQ5pqwPKtiiykeyoSJMe/5a/TmjqCCPYqfdL+OHg48Y4fGE0s5dV5/b0ZhUqVZtReXpMLrLV+/eaUkW6bE6U5ZagQ0cImVWusV2ggo6yz7wEKjlTuUOIYTzNXUfoE2pbHP5iaDKsn88mBWdgYMIf5cYyxcZHKjkg/6ZjX2+l0NtRyBgXlc6ek01L4mcvIt9KB71vQNPhY6ZNizLJDiTfeoKsKmf44278sOkmCWhFE23Htv9j3jqOcZhgp8kKt/hbTr5paTwR/8cu72DoYBind5YcKEx8hfoaqMGPiuaDCdnxN1uDIlqzY9d2Djvaagg2bugZGuwJoOYcjdedBS0quSn//eHU4+MCA7TmA++MdRUmAr4cEiGqW0GbVQtlMxCfbtM08YWwrYqNfXK4las96vJNirkZWBttlYvPBtYL6tLC3wIHgk78wnKRJg0mtlhQ5a6qBMa5iV9y37TeIodxzPEV37JaFgLTetqVVsOksrj5i5qPHeQey/911CA=
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script:
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c  "mvn deploy --settings
  target/travis/settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash -c "mvn clean install" ;fi
