server:
  port: 9191

deployer:
  main:
    config:
      folderPath: config
    target:
      idPattern: (\w+)\-?(\w?)
      config:
        folderPath: ${deployer.main.config.folderPath}/targets
        baseYaml:
          location: classpath:base-target.yaml
          overrideLocation: file:${deployer.main.target.config.folderPath}/base-target.yaml
        baseContext:
          location: classpath:base-target-context.xml
          overrideLocation: file:${deployer.main.target.config.folderPath}/base-target-context.xml
        templates:
          location: classpath:templates/targets
          overrideLocation: file:${deployer.main.config.folderPath}/templates/targets
          encoding: UTF-8
          default: default
          suffix: -target-template.yaml
      scan:
        scheduling:
          enabled: true
          cron: '0 * * * * *'
    deployment:
      folderPath: deployments
      output:
        folderPath: output
      processedCommits:
        folderPath: processed-commits
    logging:
      folderPath: logs
    scheduling:
      poolSize: 10

spring:
  freemarker:
    checkTemplateLocation: false