server:
  port: 9191

deployer:
  main:
    configFolderPath: config
    outputFolderPath: output
    baseTargetConfig:
      yamlLocation: classpath:base-target.yaml
      yamlOverrideLocation: file:${deployer.main.configFolderPath}/base-target.yaml
      appContextLocation: classpath:base-target-context.xml
      appContextOverrideLocation: file:${deployer.main.configFolderPath}/base-target-context.xml

spring:
  freemarker:
    checkTemplateLocation: false

logging:
  level:
    org.craftercms.deployer: DEBUG