server:
  port: 9191

deployer:
  main:
    config:
      path: config
      target:
        base:
          yamlLocation: classpath:base-target.yaml
          yamlOverrideLocation: file:${deployer.main.config.path}/base-target.yaml
          appContextLocation: classpath:base-target-context.xml
          appContextOverrideLocation: file:${deployer.main.config.path}/base-target-context.xml
    output:
      path: output
    logging:
      path: logs
    scheduledJob:
      cron: '0 * * * * *'

spring:
  freemarker:
    checkTemplateLocation: false