server:
  port: 9191

deployer:
  configLocation: file:config
  baseTargetConfig:
    yamlLocation: classpath:base-target.yaml
    yamlOverrideLocation: ${deployer.configLocation}/base-target.yaml
    appContextLocation: classpath:base-target-context.xml
    appContextOverrideLocation: ${deployer.configLocation}/base-target-context.xml

logging.level.org.craftercms.deployer: DEBUG